version: '3.7'

services:
  api:
    build:
      context: .
    container_name: meetings-api
    image: meetings-api:latest
    user: '1000:1000'
    dns: 8.8.8.8
    networks:
      - meetings-network
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres:11.9
    container_name: meetings-db
    ports:
      - 5432:5432
    networks:
      - meetings-network
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: meetings-db
    volumes:
      - pg:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:4.30
    container_name: meetings-pgadmin
    ports:
      - 6400:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - meetings-network
    depends_on:
      - db

networks:
  meetings-network:
    driver: bridge

volumes:
  pgadmin:
    driver: local

  pg:
    driver: local

